[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/php-fpm.err.log
stdout_logfile=/var/log/supervisor/php-fpm.out.log

[program:queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --queue=default --tries=3 --sleep=3 --timeout=90 --max-time=3600
autostart=true
autorestart=true
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/queue-default.log
stopwaitsecs=120

[program:queue-notifications]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --queue=notifications --tries=3 --sleep=3 --timeout=60 --max-time=3600
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/queue-notifications.log
stopwaitsecs=120
